// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20b4ha2a8w8-4xl2gJlY94_FScYvUbfM',
    appId: '1:779218708837:web:4ead7dbc8040876fa7d98c',
    messagingSenderId: '779218708837',
    projectId: 'imran-khan-pjt-d5bca',
    authDomain: 'imran-khan-pjt-d5bca.firebaseapp.com',
    storageBucket: 'imran-khan-pjt-d5bca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJFX7znnjhby9A3TYvdMo5qhVCckAgdI',
    appId: '1:779218708837:android:8a6cf06f324ea6b3a7d98c',
    messagingSenderId: '779218708837',
    projectId: 'imran-khan-pjt-d5bca',
    storageBucket: 'imran-khan-pjt-d5bca.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC20b4ha2a8w8-4xl2gJlY94_FScYvUbfM',
    appId: '1:779218708837:web:344a01b29ce56d5ba7d98c',
    messagingSenderId: '779218708837',
    projectId: 'imran-khan-pjt-d5bca',
    authDomain: 'imran-khan-pjt-d5bca.firebaseapp.com',
    storageBucket: 'imran-khan-pjt-d5bca.appspot.com',
  );
}
